### ISSUE TITLE
ECDH FIPS test failure in openssl build

### ISSUE THREAD

**Issue by Li-Aaron** [DMTF/libspdm#3298]
## Problem statement

FIPS test failed with `ECDH KAT failed` in openssl build.
Same test passed with mbedtls build.

> ```
> [==========] spdm_crypt_lib_tests: Running 1 test(s).
> [ RUN      ] libspdm_test_fips
> [  ERROR   ] --- status
> ECDH KAT failed 
> [   LINE   ] --- D:\a\libspdm\libspdm\unit_test\test_spdm_fips\test_spdm_fips.c:23: error: Failure!
> [  FAILED  ] libspdm_test_fips
> [  PASSED  ] 0 test(s).
> [==========] spdm_crypt_lib_tests: 1 test(s) run.
> [  FAILED  ] spdm_crypt_lib_tests: 1 test(s), listed below:
> [  FAILED  ] libspdm_test_fips
> ```

 _Originally posted by @Li-Aaron in [#3289](https://github.com/DMTF/libspdm/issues/3289#issuecomment-3400005345)_

## Debug status

At `EVP_PKEY_derive(ctx, key, key_size)`
the consumed private key is `((PROV_ECDH_CTX*)ctx->op.kex.algctx)->k`, which is same with `ctx->pkey->keydata`
the consumed peer public key is `((PROV_ECDH_CTX*)ctx->op.kex.algctx)->peerk`, which is same with `ctx->peerkey->keydata`

however, the actual private key is stored in `ctx->pkey->legacy_cache_pkey.ec`
the `ctx->pkey->keydata` contains only garbage value.

**Comment by jyao1** [comment]
It seems the regression is caused by https://github.com/DMTF/libspdm/pull/3201.
@itsManjeet , would you please take a look?
